DDaiso/urls.py
from django.conf import settings
from django.conf.urls.static import static

import product.views
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # path('', product.views.ProductListView.as_view(), name='home'),
    path('', product.views.list_product, name='home'),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from product import views

app_name = 'product'

urlpatterns = [
    path('list/', views.ProductListView.as_view(), name='list'), #product:list
    path('list2/', views.list_product, name='list2'), #product:list2
    path('detail/<int:pk>/', views.ProductDetailView.as_view(), name='detail'), #product:detail
    path('detail2/<int:pk>/', views.detail_product, name='detail2'), #product:detail2
    path('add/', views.ProductCreateView.as_view(), name='add'), #product:add
    path('add2/', views.create_product, name='add2'), #product:add2
    path('edit/<int:pk>/', views.ProductUpdateView.as_view(), name='edit'), #product:edit
    path('edit2/<int:pk>/', views.update_product, name='edit2'), #product:edit2
    path('remove/<int:pk>/', views.ProductDeleteView.as_view(), name='remove'), #product:remove
    path('remove2/<int:pk>/', views.delete_product, name='remove2'), #product:remove2
]

product/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Model
from django.shortcuts import resolve_url


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=20)
    price = models.IntegerField(validators=[MinValueValidator(0)]) #PositiveInteger()
    image = models.ImageField(upload_to='product_images/%Y/%m/%d/', null=True, blank=True)

    def __str__(self):
        return f'{self.name} : {self.price}원'

    def get_absolute_url(self):  # 모델 하나를 구하는 절대 주소
        return resolve_url('product:detail', pk=self.id)


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE) #1:N 관계
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.contents}'


    class Meta:
        ordering = ['-updated_at'] # 수정된 날짜시간 역순(최신순)

product/forms.py
from django import forms

from product.models import Product


class ProductCreationForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'image']   #__all__

    def save(self, commit=True):
        # submit버튼을 눌렀을 때 작동
        new_product = Product.objects.create(
            name=self.cleaned_data.get('name'), # 사용자가 입력한 내용을 clean_name()으로 공백제거 가능
            price=self.cleaned_data.get('price'), # 사용자가 입력한 내용을 clean_name()으로 공백제거 가능
            image=self.cleaned_data.get('image'),
        )
        return new_product

class ProductChangeForm(forms.ModelForm):
    name = forms.CharField(label='제품명', widget=forms.TextInput)
    price = forms.IntegerField(label='가격', widget=forms.NumberInput)
    class Meta:
        model = Product
        fields = ['name', 'price', 'image'] #'__all__

product/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from product.forms import ProductCreationForm, ProductChangeForm
from product.models import Product


class ProductListView(ListView):
    model = Product
    #'product_list.html', {product_list' : Product.objets.all()}
    paginate_by = 3

def list_product(request):
    product_list = Product.objects.all() #DB에 있는 product 전체 가져오자
    context = {'product_list' : product_list} #product_list라는 키로 놓자
    #product/product_list.html에 보내자
    return render(request, 'product/product_list.html', context)


class ProductDetailView(DetailView):
    model = Product
    #'product_detail.html' {'product': Product.objects.get(pk=pk)} pk = 'primary key'

def detail_product(request, pk):
    # DB에서 pk가 pk인 product 하나 가져오자
    # product_detail.html에게 product라는 변수로 product를 보내자
    product_detail = Product.objects.get(pk=pk)
    context = {'product' : product_detail}
    return render(request, 'product/product_detail.html', context)

class ProductCreateView(CreateView):
    model = Product
    fields = ['name', 'price']  #'__all__'
    template_name_suffix = '_create'    #product_form.html -> product_create.html
    success_url = reverse_lazy('product:list')  #추가 성공하면, 이동할 url 이름

def create_product(request):
    if request.method == 'POST': #사용자가 입력하고 submit 버튼 눌렀을 때
        form = ProductCreationForm(request.POST, request.FILES) #주의! files는 request.FILES로 꼭 지정해줘야함.
        if form.is_valid(): #form 검사
            form.save() #form에 있는 정보 저장
        return redirect('product:list2') #저장하고 product_list2로 넘어가기
    else: # 처음에 빈 폼 보여주기
        form = ProductCreationForm()
    return render(request, 'product/product_create.html', {'form': form})

class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name', 'price']
    template_name_suffix = '_update'  #product_form.html -> product_update.html
    # 일반적으로 성공하면 detail로 간다
    # success_url = reverse_lazy('product:list') #수정 성공하면, 이동할 url 이름

def update_product(request, pk):
    product = Product.objects.get(pk=pk)
    if request.method == 'POST':    #사용자가 입력하고 submit 버튼을 눌렀을 때
        #form에 있는 내용 가져오기
        form = ProductChangeForm(request.POST, request.FILES, instance=product)
        if form.is_valid(): #form 검사
            # selected_product = Product.objects.get(pk=pk)   #pk로 Product에서 하나 꺼내기
            # selected_product.name = form.cleaned_data.get('name')   #입력한 내용으로 Product 내용 수정
            # selected_product.price = form.cleaned_data.get('price')
            # selected_product.save() # product 저장
            form.save()
    else:
        #처음에 선택한 내용을 폼으로 보여주자
        selected_product = Product.objects.get(pk=pk)   #pk로 Product에서 하나 꺼내자 -- DB select문
        form = ProductChangeForm(instance=selected_product)     #form에 표시하자

    return render(request, 'product/product_update.html', {'form' : form})


class ProductDeleteView(DeleteView):
    model = Product
    # 삭제할 항목만 알면 되기 때문에 fields는 필요없음.
    success_url = reverse_lazy('product:list') #삭제 성공하면 이동할 url 이름
    #product_confirm_delete.html

def delete_product(request, pk):
    if request.method == 'POST':    # 진짜 삭제하기 버튼 눌렀을 때
        product = Product.objects.get(pk=pk) # pk로 Product 하나 가져오기
        product.delete() # pk로 가져온 Product 삭제
        return redirect('product:list2')
    else:
        product = Product.objects.get(pk=pk)
    return render(request, 'product/product_confirm_delete.html', {'product' : product})

product/templates/product/product_confirm_delete.html
{% extends 'base.html' %}
{% block tilte %}Remove Product{% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ product }}, 이거 진짜 지울거야?
    <div>
        {% if product.image %}
            <img src="{{ product.image.url }}" alt="{{ product }}" class="image-detail" />
        {% else %}
            제품 사진 없음
        {% endif %}
    </div>
    <input type="submit" value="찐?" class="btn btn-danger">
    <input type="button" value="취소" onclick="history.back();" class="btn btn-warning">
</form>
</body>
</html>
{% endblock %}

product/templates/product/product_create.html
{% extends 'base.html' %}

{% block title %}Add Product {% endblock %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" class="btn btn-success">
</form>
{% endblock %}

product/templates/product/product_detail.html
{% extends 'base.html' %}

{% block title %}Product Detail {% endblock %}

{% block content %}
<h1> {{ product }} </h1>
<ul>
    <li>{{ product.id }}</li>
    <li>
        {% if product.image %}
            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="image-detail">
        {% else %}
            사진 없음
        {% endif %}
    </li>
    <li>{{ product.name }}</li>
    <li>{{ product.price }}원</li>
</ul>
<a href="{% url 'product:edit2' pk=product.id %}" class="btn btn-primary">EDIT</a>
<a href="{% url 'product:list2' %}" class="btn btn-warning">Go to Product List</a>
{% endblock %}

product/templates/product/product_list.html
{% extends 'base.html' %}

{% block title %}Product List{% endblock %}
<!-- Product_list: Product.objects.all(): DB에 있는 모든 Product 꺼내서 변수에 넣어줌 -->
{% block content %}
<a href="{% url 'product:add2' %}" class="btn btn-success">Add Product</a>
<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>제품사진</th>
        <th>제품명</th>
        <th>가격</th>
        <th>EDIT</th>
        <th>REMOVE</th>
    </tr>
    </thead>
    <tbody>
    {% for product in product_list %}
    <tr>
        <td class="align-middle">{{ forloop.counter }}</td>
        <td class="align-middle">
            {% if product.image %}
                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="image-list"/>
            {% else %}
                제품사진 없음
            {% endif %}
        </td>
        <td class="align-middle"><a href="{% url 'product:detail2' pk=product.id %}">{{ product.name }} (상품평: {{ product.review_set.all.count }})</a></td>
        <td class="align-middle">{{ product.price }}원</td>
        <td class="align-middle"><a href="{% url 'product:edit2' pk=product.id %}" class="btn btn-primary">EDIT</a></td>
        <td class="align-middle"><a href="{% url 'product:remove2' pk=product.id %}" class="btn btn-danger">REMOVE</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

product/templates/product/product_update.html
{% extends 'base.html' %}

{% block title %}Product Update{% endblock %}
{% block content %}
<body>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Edit" class="btn btn-primary">
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- bootstrap css 추가 -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}

    {% block pagination %}
        {% if is_paginated %}
            <ul class="pagination justify-content-center">
                <!-- 이전 -->
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}" class="page-link">이전</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a href="#" class="page-link">이전</a>
                    </li>
                {% endif %}
                <!-- page -->
                {% for object in page_obj.paginator.page_range %}
                    {% if page_obj.number == forloop.counter %}
                        <!-- URL/?page=숫자 -->
                       <li class="page-item">
                           <a href="{{ request.path }}?page={{ forloop.counter }}" class="page-link disabled">{{ forloop.counter }}</a>
                       </li>
                    {% else %}
                        <li class="page-item">
                           <a href="{{ request.path }}?page={{ forloop.counter }}" class="page-link">{{ forloop.counter }}</a>
                       </li>
                    {% endif %}
                {% endfor %}
                <!-- 다음 -->
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}" class="page-link">다음</a>
                    </li>
                {% else %}
                     <li class="page-item">
                        <a href="#" class="page-link disabled">다음</a>
                    </li>
                {% endif %}
            </ul>
        {% endif %}
    {% endblock %}
</body>
<!-- bootstrap js 추가 -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</html>